WEB/FirstService/urls.py
from django.urls import path

from FirstService import views

app_name = 'FirstService'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('select/', views.select, name='select'),
    path('upload/', views.upload, name='upload'),
    path('upload2/', views.upload2, name='upload2'),
    path('upload3/', views.upload3, name='upload3'),
    path('upload_create', views.upload_create, name='upload_create'),
    path('upload_create2', views.upload_create2, name='upload_create2'),
    path('upload_create3', views.upload_create3, name='upload_create3'),
    path('learning/<int:pk>', views.learning, name='learning'),
    path('result/<int:pk>', views.result, name='result'),
]

WEB/Web_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from FirstService import views
from FirstService.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('FirstService/', include('FirstService.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/FirstService/models.py
from django.db import models
from io import BytesIO
import sys
from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image
# Create your models here.


class Profile(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', null=True)
    image_converted =models.ImageField(upload_to='images/', null=True)

    def save(self, *args, **kwargs):
        self.convert_image()
        self.image = None
        super(Profile, self).save(*args, **kwargs)

    def convert_image(self, *args, **kwargs):
        image_converted = convert_test(self.image)
        self.image_converted = InMemoryUploadedFile(file=image_converted,
                                                    field_name="ImageField",
                                                    name=self.image.name,
                                                    content_type='image/jpeg',
                                                    size=sys.getsizeof(image_converted),
                                                    charset=None)

def convert_test(img):
    img = Image.open(img)
    img = img.convert('RGB')
    img = img.resize((300, 300), Image.ANTIALIAS)
    return image_to_bytes(img)

def image_to_bytes(img):
    output = BytesIO()
    img.save(output, format='JPEG', quality=95)
    output.seek(0)
    return output


class Result(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='imagesResult/', null=True)

    def __str__(self):
        return self.title

WEB/FirstService/views.py
from django.shortcuts import render, redirect
from io import BytesIO
import sys, os
from django.core.files.uploadedfile import InMemoryUploadedFile
# Create your views here.
from FirstService.models import Profile,Result
from PIL import Image
import requests
from django.conf import settings




# ssh -i flask_model.pem ubuntu@13.59.5.227

# python test.py



def home(request):

    return render(request, 'home.html')

def upload(request):

    return render(request, 'upload.html')

def upload2(request):

    return render(request, 'upload2.html')

def upload3(request):

    return render(request, 'upload3.html')

def select(request):

    return render(request, 'select.html')

def upload_create(request):

    form = Profile()
    form.image= request.FILES['image']
    form.save()

    profile = Profile.objects.get(id=form.id)

    temp = profile.image_converted.name
    try:
        resp = requests.post("http://3.16.37.62:5000/predict1",
                             files={"file": open(os.path.join(settings.BASE_DIR, 'media', temp), 'rb')})

        save_path = os.path.join(settings.BASE_DIR, "media", "temp", "result" + str(profile.id) + ".jpg")
        photo = open(save_path, 'wb')
        photo.write(resp.content)
        photo.close()


        return render(request, 'loading.html', {'profile':profile})
    except:
        return redirect('FirstService:home')

def upload_create2(request):

    form = Profile()
    form.image= request.FILES['image']
    form.save()

    profile = Profile.objects.get(id=form.id)

    temp = profile.image_converted.name

    try:
        resp = requests.post("http://3.16.37.62:5000/predict1",
                             files={"file": open(os.path.join(settings.BASE_DIR, 'media', temp), 'rb')})

        save_path = os.path.join(settings.BASE_DIR, "media", "temp", "result" + str(profile.id) + ".jpg")
        photo = open(save_path, 'wb')
        photo.write(resp.content)
        photo.close()


        return render(request, 'loading.html', {'profile':profile})
    except:
        return redirect('FirstService:home')

def upload_create3(request):

    form = Profile()
    form.image= request.FILES['image']
    form.save()

    profile = Profile.objects.get(id=form.id)

    temp = profile.image_converted.name

    try:
        resp = requests.post("http://3.16.37.62:5000/predict1",
                             files={"file": open(os.path.join(settings.BASE_DIR, 'media', temp), 'rb')})

        save_path = os.path.join(settings.BASE_DIR, "media", "temp", "result" + str(profile.id) + ".jpg")
        photo = open(save_path, 'wb')
        photo.write(resp.content)
        photo.close()


        return render(request, 'loading.html', {'profile':profile})
    except:
        return redirect('FirstService:home')

def learning(request, **kwargs):
    result_img = Result()
    profile = Profile.objects.get(id=kwargs['pk'])

    # 이미지 변환 코드

    save_path = os.path.join(settings.BASE_DIR, "media", "temp", "result" + str(profile.id)+".jpg")

    image = Image.open(save_path)
    image = image.convert('RGB')
    image = image.resize((300, 300), Image.ANTIALIAS)
    output = BytesIO()
    image.save(output, format='JPEG', quality=85)
    output.seek(0)
    result_img.image = InMemoryUploadedFile(output, 'ImageField',
                                str(profile.id)+".jpg",
                                'image/jpeg',
                                sys.getsizeof(output), None)

    result_img.save()

    return redirect('FirstService:result', pk=result_img.id)


def result(request, **kwargs):
    result = Result.objects.get(id=kwargs['pk'])
    return render(request, 'result.html', {'result':result})

WEB/FirstService/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <section class="pekecontainer">

      <div class="peke_frame">
        <div class="stat_img">
          <img src="/static/image/main_stat.png">
        </div>
        <div class="banner_img">
          <img src="/static/image/pecat.png">
        </div>
        <div class="text_container">
          <div class="text_box1">
            <div class="text_p">반려동물과 <br><br>이모티콘 만들러 가기!</div>
          </div>
          <div class="text_box2">
            <div class="go"><a href="{% url 'FirstService:select' %}">GO !</a></div>
            <div class="go">YES !</div>
          </div>
        </div>
      </div>

      <!-- <div class="team_container">

      </div> -->
    </section>


{% endblock content %}

WEB/FirstService/templates/loading.html
{% extends 'base.html' %}

{% block content %}

<div class="box">
    <div class="cat" >
        <div class="cat__body"></div>
        <div class="cat__body"></div>
        <div class="cat__tail"></div>
        <div class="cat__head"></div>
    </div>
</div>
    <script>
        setTimeout(function (){
            window.location.href = '{% url 'FirstService:learning' pk=profile.id %}'
        },3000)
    </script>


{% endblock content %}

WEB/FirstService/templates/result.html
{% extends 'base.html' %}

{% block content %}

        <section class="result_container">
        <div class="result_frame">
            <div class="text_box">
                <div class="step_2"># STEP 2</div>
                <div class="text">RESULT PEKEMON</div>
            </div>
            <div class="line_dot">
                <img style="margin:0.7rem 0.65rem; height: 90%; width:90%;" src="{{ result.image.url }}">
            </div>
{#            <div class="icon_box_1">#}
{#                <li><a href="#"><i class="fab fa-brands fa-twitter"></i></a></li>#}
{#            </div>#}
{#            <div class="icon_box_2">#}
{#                <li><a href="#"><i class="fab fa-brands fa-facebook-f"></i></a></li>#}
{#            </div>#}
{#            <div class="icon_box_3">#}
{#                <li><a href="#"><i class="fab fa-brands fa-line"></i></a></li>#}
{#            </div>#}
            <div>
                <div id="label-container" class="d-flex flex-column justify-content-around"></div>
                <div style="text-align: center;" id="addThis" class="addthis_inline_share_toolbox_6lz1"></div>
            </div>

            <div class="save_btn">
                <li><a href="{{ result.image.url }}" download="#">저장하기</a></li>
            </div>
            <div class="re_btn">
                <li><a href="{% url 'FirstService:home' %}">다시하기</a></li>
            </div>



        </div>


    </section>
    
{% endblock content %}

WEB/FirstService/templates/select.html
{% extends 'base.html' %}

{% block content %}
    <section class="option_container">
        <div class="option_frame">
            <div class="text_box">
                <div class="step_2"># STEP 0</div>
                <div class="text">SELECT OPTION!</div>
                <div class="warning_box">※ 좌측 상단 이미지의 경우 기본 이미지입니다 ※</div>
            </div>
            <div class="line_dot"></div>
            <div class="icon_box_1">
                <li><a href="#"><img src="../../static/image/option_1.png"></a></li>
            </div>
            <div class="icon_box_2">
                <li><a href="{% url 'FirstService:upload' %}"><img src="../../static/image/option_2.png"></a></li>
            </div>
            <div class="icon_box_3">
                <li><a href="{% url 'FirstService:upload2' %}"><img src="../../static/image/option_3.png"></a></li>
            </div>
            <div class="icon_box_4">
                <li><a href="{% url 'FirstService:upload3' %}"><img src="../../static/image/option_4.png"></a></li>
            </div>

        </div>


    </section>

{% endblock content %}

WEB/FirstService/templates/upload.html
{% extends 'base.html' %}

{% block content %}

    <section class="upload_container">
        <div class="upload_frame">
            <div class="text_box">
                <div class="step_2"># STEP 1</div>
                <div class="text">UPLOAD IMAGE</div>
            </div>
            <div class="line_dot">
                <img id="uploaded_img">
            </div>
            <form action="{%url 'FirstService:upload_create'%}" method="post" enctype="multipart/form-data" class="filebox">
                {% csrf_token %}
                <label for="ex_file">Select from the library</label>
                <input type="file" name="image" id="ex_file">
                <input type="submit" value="Submit" class="submit_btn" id="submit_btn">
            </form>

        </div>

    </section>

{% endblock content %}

WEB/FirstService/templates/upload2.html
{% extends 'base.html' %}

{% block content %}

    <section class="upload_container">
        <div class="upload_frame">
            <div class="text_box">
                <div class="step_2"># STEP 1</div>
                <div class="text">UPLOAD IMAGE</div>
            </div>
            <div class="line_dot">
                <img id="uploaded_img">
            </div>
            <form action="{%url 'FirstService:upload_create2'%}" method="post" enctype="multipart/form-data" class="filebox">
                {% csrf_token %}
                <label for="ex_file">Select from the library</label>
                <input type="file" name="image" id="ex_file">
                <input type="submit" value="Submit" class="submit_btn" id="submit_btn">
            </form>

        </div>

    </section>

{% endblock content %}

WEB/FirstService/templates/upload3.html
{% extends 'base.html' %}

{% block content %}

    <section class="upload_container">
        <div class="upload_frame">
            <div class="text_box">
                <div class="step_2"># STEP 1</div>
                <div class="text">UPLOAD IMAGE</div>
            </div>
            <div class="line_dot">
                <img id="uploaded_img">
            </div>
            <form action="{%url 'FirstService:upload_create3'%}" method="post" enctype="multipart/form-data" class="filebox">
                {% csrf_token %}
                <label for="ex_file">Select from the library</label>
                <input type="file" name="image" id="ex_file">
                <input type="submit" value="Submit" class="submit_btn" id="submit_btn">
            </form>

        </div>

    </section>

{% endblock content %}

WEB/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

{% include 'head.html' %}

<body>

{% include 'header.html' %}

    <div class="inside_hr">
        {% block content %}

        {% endblock %}
        <p class="team_name">Made by 참새에 방앗GAN</p>
        {#    static java link#}
        <script type="text/javascript" src="{% static 'javascript/allfunc.js' %}"></script>
    </div>


</body>
</html>

WEB/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/2d323a629b.js" crossorigin="anonymous"></script>
    {# bootstrap Link #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# jquery link #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script
        type="text/javascript"
        src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e64b3727e862b06"
    ></script>

    {# static css link#}
    <link rel="stylesheet" type="text/css" href="{% static "base.css" %}">

    {# 웹사이트 최상단 title #}
    <title>펫 이모티콘 만들기</title>
    <meta name="title" content="펫 이모티콘 만들기" />

</head>

WEB/templates/header.html
 <nav class="navbar">
        <!-- Logo with text -->
        <div class="navbar__logo">
            <i class="fas fa-solid fa-paw"></i>

            <a href="{% url 'home' %}">Pekemon!</a>
        </div>
        <!-- Menu -->
        <ul class="navbar__menu">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'home' %}">Gallery</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
        </ul>
        <!-- Icons -->
        <ul class="navbar__icons">
            <li><i class="fab fa-twitter"></i></li>
            <li><i class="fab fa-facebook-f"></i></li>
        </ul>
        <!-- Toggle button -->
        <a href="#" class="navbar__toggleBtn">
            <i class="fas fa-bars"></i>
        </a>
    </nav>